# -*- coding: utf-8 -*-
"""spatialisation sonore.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12HJeFH02OkM8yMpj2lupg8Z4TbVexMhl
"""

import numpy as np
import scipy as sp
import scipy.io.wavfile as spiow
import scipy.signal as spsig
import math
import matplotlib.pyplot as plt

Fs,x = spiow.read('mono_left.wav') 
Fss,y=spiow.read('mono_right.wav')

x = np.array(x,dtype='int64')
y= np.array(y,dtype='int64')
print("entrez la distance")
dist = float(input())

N = len(x)
dur = N/Fs
t = np.arange(0,dur,1/Fs)

Cxx = spsig.correlate(x,y,'full')
t_Cxx = np.arange(-dur+1/Fs,dur-1/Fs,1/Fs)
print(t_Cxx[Cxx.argmax()])
rad=math.acos((340*t_Cxx[Cxx.argmax()])/dist)
angle=np.degrees(rad)
print(angle)
if(len(t_Cxx)!=len(Cxx)):
    for i in range(0,abs(len(t_Cxx)-len(Cxx))):
        t_Cxx=np.append(t_Cxx,0)

#t_Cxx=np.append(t_Cxx,0)
plt.figure(figsize=(8,6))
plt.plot(t_Cxx,Cxx,'k')
plt.grid()
plt.xlabel('time shift (s)')
plt.ylabel('Autocorrelation')
plt.xlim([-dur,dur])
#plt.xlim([-0.0025,0.0025])
plt.show()
